### ISSUE TITLE
rake assets:precompile does not 'stitch' the coffeescript

### ISSUE THREAD

**Issue by ricktessner** [doitian/stitch_rails#3]
I found that when I deploy my app to heroku, which runs the rake task, assets:precompile, that the coffeescript does not get 'stitched'.

Trying it localling and adding a couple of puts in the railtie.rb shows that the config.before_configuration method is run but nothing else is ever called.

AIs there a simple configuration option that I'm missing somewhere?

Thanks,

Rick

**Comment by doitian** [comment]
Is the gem in group `assets`?
